current_index: 26
filename: ../tagged2iteration/1000simpleTagged_es
source_lang: auto
tags:
  - vaccines
  - vaccination
  - mental-health
  - school-reopening
  - household-violence
  - NONE
target_lang: es
translate: false
