current_index: 250
filename: ../tagged2iteration/1000simpleTagged_fr
source_lang: auto
tags:
- vaccines
- vaccination
- mental-health
- school-reopening
- household-violence
- NONE
target_lang: es
translate: true
